### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation:

### ISSUE THREAD

**Issue by andrerspcorreia** [takase/control-length#6]
Hello! I was trying to run your code but ran into problems.
I'm using cuda 10.1 and pytorch 1.7.0+cu92

Running train.py with the recommened parameters results in running out of memory:

python3 train.py data-bin/writingPrompts --source-lang wp_source --target-lang wp_target --arch transformer_wmt_en_de --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 --lr-scheduler inverse_sqrt --warmup-init-lr 1e-07  --warmup-updates 4000 --lr 0.001 --min-lr 1e-09 --dropout 0.3 --weight-decay 0.0 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --seed 2723 --max-epoch 100 --update-freq 64 --share-all-embeddings --represent-length-by-lrpe --ordinary-sinpos --save-dir output --max-tokens 3584

 
Lowering the parameters to avoid running out of memory as such:

python3 train.py data-bin/writingPrompts --source-lang wp_source --target-lang wp_target --arch transformer_wmt_en_de --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 --lr-scheduler inverse_sqrt --warmup-init-lr 1e-07  --warmup-updates 4000 --lr 0.001 --min-lr 1e-09 --dropout 0.3 --weight-decay 0.0 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --seed 2723 --max-epoch 100 --update-freq 64 --share-all-embeddings --represent-length-by-lrpe --ordinary-sinpos --save-dir output --max-tokens 224 --max-sentences 128

Results in the following error:

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [30, 7, 1536]], which is output 0 of AddBackward0, is at version 2; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

Full Output:

| [wp_source] dictionary: 899328 types
| [wp_target] dictionary: 899328 types
| data-bin/writingPrompts train 272600 examples
| data-bin/writingPrompts valid 15620 examples
| model transformer_wmt_en_de, criterion LabelSmoothedCrossEntropyCriterion
| num. model params: 504594432
| training on 1 GPUs
| max tokens per GPU = 224 and max sentences per GPU = 128
| WARNING: 51452 samples have invalid sizes and will be skipped, max_positions=(1024, 1024), first few sample ids=[185425, 210272, 169339, 79302, 184940, 229390, 23406, 81508, 81486, 128160]
| NOTICE: your device may support faster training with --fp16
/home/andre/Documents/control-length/encdec/fairseq/modules/multihead_attention.py:109: UserWarning: Output 0 of SplitBackward is a view and is being modified inplace. This view is an output of a function that returns multiple views. Inplace operators on such views are being deprecated and will be forbidden starting from version 1.8. Consider using `unsafe_` version of the function that produced this view or don't modify this view inplace. (Triggered internally at  /pytorch/torch/csrc/autograd/variable.cpp:491.)
  q *= self.scaling
[W python_anomaly_mode.cpp:104] Warning: Error detected in SplitBackward. Traceback of forward call that caused the error:
  File "train.py", line 365, in <module>
    main(args)
  File "train.py", line 84, in main
    trainer.dummy_train_step([dummy_batch])
  File "/home/andre/Documents/control-length/encdec/fairseq/trainer.py", line 329, in dummy_train_step
    self.train_step(dummy_batch, dummy_batch=True)
  File "/home/andre/Documents/control-length/encdec/fairseq/trainer.py", line 175, in train_step
    loss, sample_size, logging_output = self.task.get_loss(
  File "/home/andre/Documents/control-length/encdec/fairseq/tasks/fairseq_task.py", line 157, in get_loss
    return criterion(model, sample)
  File "/home/andre/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/andre/Documents/control-length/encdec/fairseq/criterions/label_smoothed_cross_entropy.py", line 36, in forward
    net_output = model(**sample['net_input'])
  File "/home/andre/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/andre/Documents/control-length/encdec/fairseq/models/fairseq_model.py", line 163, in forward
    decoder_out = self.decoder(prev_output_tokens, target_length, encoder_out)
  File "/home/andre/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/andre/Documents/control-length/encdec/fairseq/models/transformer.py", line 507, in forward
    x, attn = layer(
  File "/home/andre/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/andre/Documents/control-length/encdec/fairseq/models/transformer.py", line 726, in forward
    x, _ = self.self_attn(
  File "/home/andre/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/andre/Documents/control-length/encdec/fairseq/modules/multihead_attention.py", line 96, in forward
    q, k, v = self.in_proj_qkv(query)
  File "/home/andre/Documents/control-length/encdec/fairseq/modules/multihead_attention.py", line 193, in in_proj_qkv
    return self._in_proj(query).chunk(3, dim=-1)
 (function _print_stack)
Traceback (most recent call last):
  File "train.py", line 365, in <module>
    main(args)
  File "train.py", line 84, in main
    trainer.dummy_train_step([dummy_batch])
  File "/home/andre/Documents/control-length/encdec/fairseq/trainer.py", line 329, in dummy_train_step
    self.train_step(dummy_batch, dummy_batch=True)
  File "/home/andre/Documents/control-length/encdec/fairseq/trainer.py", line 200, in train_step
    raise e
  File "/home/andre/Documents/control-length/encdec/fairseq/trainer.py", line 189, in train_step
    self.optimizer.backward(loss)
  File "/home/andre/Documents/control-length/encdec/fairseq/optim/fairseq_optimizer.py", line 73, in backward
    loss.backward()
  File "/home/andre/.local/lib/python3.8/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/andre/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 130, in backward
    Variable._execution_engine.run_backward(
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [30, 7, 1536]], which is output 0 of AddBackward0, is at version 2; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

Any idea on what the problem might be? Cheers!

**Comment by takase** [comment]
Thank you for your interest in our study.

What is dataset you used?
I think your dictionary (vocabulary) size is too large and thus, out of memory error is happened.

**Comment by andrerspcorreia** [comment]
Thank you for your answer, I used WrittingPrompts from here https://dl.fbaipublicfiles.com/fairseq/data/writingPrompts.tar.gz.

**Comment by takase** [comment]
I'm not familiar with the dataset. So, if you want to apply a neural encoder-decoder to the dataset, I recommend asking the publisher of the dataset.
As described, I think your vocabulary size is too large, thus, recommend using subword such as BPE or sentencepiece to construct vocabulary.

**Comment by andrerspcorreia** [comment]
Ok thanks. What dataset did you use? Is it available for public use?

**Comment by takase** [comment]
We conducted experiments on summarization as described in our paper: https://www.aclweb.org/anthology/N19-1401.pdf
We used Annotated English Gigaword which is not publicly available officially but distributed in https://github.com/harvardnlp/sent-summary
The above distributed dataset might be pre-processed but we need to construct subword vocabulary for encoder-decoders.

**Comment by andrerspcorreia** [comment]
Thank you, reducing the dataset size did it.
